"""add_baby_achievements_table

Revision ID: 2a80d4519792
Revises: 9952986ff200
Create Date: 2026-03-10 23:03:22.064111+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a80d4519792'
down_revision: Union[str, Sequence[str], None] = '9952986ff200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baby_achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.String(length=50), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_baby_achievements_baby_id_babies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_baby_achievements_triggered_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baby_achievements')),
    sa.UniqueConstraint('baby_id', 'achievement_id', name='uix_baby_achievement')
    )
    op.create_index('idx_baby_achievements_baby_id', 'baby_achievements', ['baby_id'], unique=False)
    op.create_index(op.f('ix_baby_achievements_baby_id'), 'baby_achievements', ['baby_id'], unique=False)
    op.create_index(op.f('ix_baby_achievements_id'), 'baby_achievements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_baby_achievements_id'), table_name='baby_achievements')
    op.drop_index(op.f('ix_baby_achievements_baby_id'), table_name='baby_achievements')
    op.drop_index('idx_baby_achievements_baby_id', table_name='baby_achievements')
    op.drop_table('baby_achievements')
    # ### end Alembic commands ###
