"""add daily_summaries table

Revision ID: 35cf117c9ca2
Revises: 86c007e59a68
Create Date: 2026-02-14 15:48:50.281327+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35cf117c9ca2'
down_revision: Union[str, Sequence[str], None] = '86c007e59a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('generated_content', sa.Text(), nullable=False),
    sa.Column('edited_content', sa.Text(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_daily_summaries_baby_id_babies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_summaries_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_summaries')),
    sa.UniqueConstraint('baby_id', 'summary_date', name='uix_daily_summary_baby_date')
    )
    op.create_index('idx_daily_summary_baby_date', 'daily_summaries', ['baby_id', 'summary_date'], unique=False)
    op.create_index(op.f('ix_daily_summaries_id'), 'daily_summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_summaries_id'), table_name='daily_summaries')
    op.drop_index('idx_daily_summary_baby_date', table_name='daily_summaries')
    op.drop_table('daily_summaries')
    # ### end Alembic commands ###
