"""add characteristics to babies

Revision ID: 52a1af06021f
Revises: 35a2216ed024
Create Date: 2026-02-14 21:45:37.022146+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a1af06021f'
down_revision: Union[str, Sequence[str], None] = '35a2216ed024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('babies', sa.Column('characteristics', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('babies', 'characteristics')
    # ### end Alembic commands ###
