"""add system_settings table

Revision ID: 7da7caae11a7
Revises: 1ed983bdc98a
Create Date: 2026-02-21 10:38:27.111459+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da7caae11a7'
down_revision: Union[str, Sequence[str], None] = '1ed983bdc98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    system_settings = op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_index(op.f('ix_app_notifications_id'), 'app_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_app_notifications_user_id'), 'app_notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Seed data
    op.bulk_insert(
        system_settings,
        [
            {"key": "llm_model", "value": "gemini-1.5-pro"},
            {"key": "ai_enabled_chat", "value": "true"},
            {"key": "ai_enabled_summary", "value": "true"},
            {"key": "ai_enabled_feedback", "value": "true"},
            {"key": "llm_temperature", "value": "0.7"},
            {"key": "llm_max_tokens", "value": "800"},
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_notifications_user_id'), table_name='app_notifications')
    op.drop_index(op.f('ix_app_notifications_id'), table_name='app_notifications')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
