"""update growth record fields

Revision ID: 87137ab3b509
Revises: a1b2c3d4e5f6
Create Date: 2026-02-13 21:29:08.388406+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87137ab3b509'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_baby_permissions_user_baby_type'), table_name='baby_permissions')
    op.drop_index(op.f('idx_diaper_baby_time'), table_name='diapers')
    op.create_index('idx_diaper_baby_time', 'diapers', ['baby_id', 'change_time'], unique=False)
    op.drop_index(op.f('idx_family_users_family_user'), table_name='family_users')
    op.drop_index(op.f('idx_feeding_baby_time'), table_name='feedings')
    op.create_index('idx_feeding_baby_time', 'feedings', ['baby_id', 'feeding_time'], unique=False)

    # Growth table renames and data migration
    op.alter_column('growths', 'measurement_date', new_column_name='date')
    op.alter_column('growths', 'height_cm', new_column_name='height')
    op.alter_column('growths', 'head_circumference_cm', new_column_name='head_circumference')
    
    op.add_column('growths', sa.Column('weight', sa.Integer(), nullable=True))
    op.execute("UPDATE growths SET weight = CAST(weight_kg * 1000 AS INTEGER)")
    op.drop_column('growths', 'weight_kg')

    op.drop_index('ix_growths_measurement_date', table_name='growths')
    op.create_index(op.f('ix_growths_date'), 'growths', ['date'], unique=False)

    op.drop_index(op.f('idx_sleep_baby_start_time'), table_name='sleeps')
    op.create_index('idx_sleep_baby_start_time', 'sleeps', ['baby_id', 'start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sleep_baby_start_time', table_name='sleeps')
    op.create_index(op.f('idx_sleep_baby_start_time'), 'sleeps', ['baby_id', sa.literal_column('start_time DESC')], unique=False)
    op.add_column('growths', sa.Column('height_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('growths', sa.Column('measurement_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('growths', sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('growths', sa.Column('head_circumference_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_growths_date'), table_name='growths')
    op.create_index(op.f('ix_growths_measurement_date'), 'growths', ['measurement_date'], unique=False)
    op.drop_column('growths', 'head_circumference')
    op.drop_column('growths', 'height')
    op.drop_column('growths', 'weight')
    op.drop_column('growths', 'date')
    op.drop_index('idx_feeding_baby_time', table_name='feedings')
    op.create_index(op.f('idx_feeding_baby_time'), 'feedings', ['baby_id', sa.literal_column('feeding_time DESC')], unique=False)
    op.create_index(op.f('idx_family_users_family_user'), 'family_users', ['family_id', 'user_id'], unique=False)
    op.drop_index('idx_diaper_baby_time', table_name='diapers')
    op.create_index(op.f('idx_diaper_baby_time'), 'diapers', ['baby_id', sa.literal_column('change_time DESC')], unique=False)
    op.create_index(op.f('idx_baby_permissions_user_baby_type'), 'baby_permissions', ['user_id', 'baby_id', 'record_type'], unique=False)
    # ### end Alembic commands ###
