"""create record_comments table

Revision ID: c37592925139
Revises: a2f4a4d8dccd
Create Date: 2026-02-16 13:49:13.433134+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c37592925139'
down_revision: Union[str, Sequence[str], None] = 'a2f4a4d8dccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_record_comments_baby_id_babies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_record_comments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_record_comments'))
    )
    op.create_index('idx_comment_record', 'record_comments', ['record_type', 'record_id'], unique=False)
    op.create_index(op.f('ix_record_comments_id'), 'record_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_comments_id'), table_name='record_comments')
    op.drop_index('idx_comment_record', table_name='record_comments')
    op.drop_table('record_comments')
    # ### end Alembic commands ###
