"""create record_comments table

Revision ID: c37592925139
Revises: a2f4a4d8dccd
Create Date: 2026-02-16 13:49:13.433134+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c37592925139'
down_revision: Union[str, Sequence[str], None] = 'a2f4a4d8dccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_families'))
    )
    op.create_index(op.f('ix_families_id'), 'families', ['id'], unique=False)
    op.create_index(op.f('ix_families_invite_code'), 'families', ['invite_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('babies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('characteristics', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_babies_family_id_families')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_babies'))
    )
    op.create_index(op.f('ix_babies_id'), 'babies', ['id'], unique=False)
    op.create_table('family_users',
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_family_users_family_id_families')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_family_users_user_id_users')),
    sa.PrimaryKeyConstraint('family_id', 'user_id', name=op.f('pk_family_users'))
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_token'), 'user_sessions', ['token'], unique=True)
    op.create_table('baby_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_baby_permissions_baby_id_babies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_baby_permissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baby_permissions')),
    sa.UniqueConstraint('baby_id', 'user_id', 'record_type', name='uix_baby_user_record_type')
    )
    op.create_index(op.f('ix_baby_permissions_id'), 'baby_permissions', ['id'], unique=False)
    op.create_table('contractions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_contractions_baby_id_babies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_contractions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contractions'))
    )
    op.create_index('idx_contraction_baby_start_time', 'contractions', ['baby_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_contractions_baby_id'), 'contractions', ['baby_id'], unique=False)
    op.create_index(op.f('ix_contractions_id'), 'contractions', ['id'], unique=False)
    op.create_index(op.f('ix_contractions_start_time'), 'contractions', ['start_time'], unique=False)
    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('generated_content', sa.Text(), nullable=False),
    sa.Column('edited_content', sa.Text(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_daily_summaries_baby_id_babies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_summaries_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_summaries')),
    sa.UniqueConstraint('baby_id', 'summary_date', name='uix_daily_summary_baby_date')
    )
    op.create_index('idx_daily_summary_baby_date', 'daily_summaries', ['baby_id', 'summary_date'], unique=False)
    op.create_index(op.f('ix_daily_summaries_id'), 'daily_summaries', ['id'], unique=False)
    op.create_table('diapers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('change_time', sa.DateTime(), nullable=False),
    sa.Column('diaper_type', sa.Enum('WET', 'DIRTY', 'BOTH', name='diapertype'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_diapers_baby_id_babies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_diapers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diapers'))
    )
    op.create_index('idx_diaper_baby_time', 'diapers', ['baby_id', 'change_time'], unique=False)
    op.create_index(op.f('ix_diapers_change_time'), 'diapers', ['change_time'], unique=False)
    op.create_index(op.f('ix_diapers_id'), 'diapers', ['id'], unique=False)
    op.create_table('feedings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feeding_time', sa.DateTime(), nullable=False),
    sa.Column('feeding_type', sa.Enum('BREAST', 'BOTTLE', 'MIXED', name='feedingtype'), nullable=False),
    sa.Column('amount_ml', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_feedings_baby_id_babies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedings'))
    )
    op.create_index('idx_feeding_baby_time', 'feedings', ['baby_id', 'feeding_time'], unique=False)
    op.create_index(op.f('ix_feedings_feeding_time'), 'feedings', ['feeding_time'], unique=False)
    op.create_index(op.f('ix_feedings_id'), 'feedings', ['id'], unique=False)
    op.create_table('growths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('head_circumference', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_growths_baby_id_babies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_growths_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growths'))
    )
    op.create_index('idx_growth_baby_date', 'growths', ['baby_id', 'date'], unique=False)
    op.create_index(op.f('ix_growths_date'), 'growths', ['date'], unique=False)
    op.create_index(op.f('ix_growths_id'), 'growths', ['id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_notes_baby_id_babies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notes_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_index(op.f('ix_notes_note_time'), 'notes', ['note_time'], unique=False)
    op.create_table('record_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_record_comments_baby_id_babies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_record_comments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_record_comments'))
    )
    op.create_index('idx_comment_record', 'record_comments', ['record_type', 'record_id'], unique=False)
    op.create_index(op.f('ix_record_comments_id'), 'record_comments', ['id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_schedules_baby_id_babies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_schedules_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_index('idx_schedule_baby_scheduled_time', 'schedules', ['baby_id', 'scheduled_time'], unique=False)
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_index(op.f('ix_schedules_scheduled_time'), 'schedules', ['scheduled_time'], unique=False)
    op.create_table('sleeps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_sleeps_baby_id_babies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sleeps_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sleeps'))
    )
    op.create_index('idx_sleep_baby_start_time', 'sleeps', ['baby_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_sleeps_id'), 'sleeps', ['id'], unique=False)
    op.create_index(op.f('ix_sleeps_start_time'), 'sleeps', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleeps_start_time'), table_name='sleeps')
    op.drop_index(op.f('ix_sleeps_id'), table_name='sleeps')
    op.drop_index('idx_sleep_baby_start_time', table_name='sleeps')
    op.drop_table('sleeps')
    op.drop_index(op.f('ix_schedules_scheduled_time'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_index('idx_schedule_baby_scheduled_time', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_record_comments_id'), table_name='record_comments')
    op.drop_index('idx_comment_record', table_name='record_comments')
    op.drop_table('record_comments')
    op.drop_index(op.f('ix_notes_note_time'), table_name='notes')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_growths_id'), table_name='growths')
    op.drop_index(op.f('ix_growths_date'), table_name='growths')
    op.drop_index('idx_growth_baby_date', table_name='growths')
    op.drop_table('growths')
    op.drop_index(op.f('ix_feedings_id'), table_name='feedings')
    op.drop_index(op.f('ix_feedings_feeding_time'), table_name='feedings')
    op.drop_index('idx_feeding_baby_time', table_name='feedings')
    op.drop_table('feedings')
    op.drop_index(op.f('ix_diapers_id'), table_name='diapers')
    op.drop_index(op.f('ix_diapers_change_time'), table_name='diapers')
    op.drop_index('idx_diaper_baby_time', table_name='diapers')
    op.drop_table('diapers')
    op.drop_index(op.f('ix_daily_summaries_id'), table_name='daily_summaries')
    op.drop_index('idx_daily_summary_baby_date', table_name='daily_summaries')
    op.drop_table('daily_summaries')
    op.drop_index(op.f('ix_contractions_start_time'), table_name='contractions')
    op.drop_index(op.f('ix_contractions_id'), table_name='contractions')
    op.drop_index(op.f('ix_contractions_baby_id'), table_name='contractions')
    op.drop_index('idx_contraction_baby_start_time', table_name='contractions')
    op.drop_table('contractions')
    op.drop_index(op.f('ix_baby_permissions_id'), table_name='baby_permissions')
    op.drop_table('baby_permissions')
    op.drop_index(op.f('ix_user_sessions_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('family_users')
    op.drop_index(op.f('ix_babies_id'), table_name='babies')
    op.drop_table('babies')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_families_invite_code'), table_name='families')
    op.drop_index(op.f('ix_families_id'), table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###
