"""add notification indexes

Revision ID: d3f4g5h6i7j8
Revises: c37592925139
Create Date: 2026-02-23 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f4g5h6i7j8'
down_revision: Union[str, Sequence[str], None] = '3bc9c82be9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_app_notifications_user_created', 'app_notifications', ['user_id', 'created_at'], unique=False)
    # idx_app_notifications_user_unread already exists from 0332ddd5a74c
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    # idx_app_notifications_user_unread should not be dropped as it existed before
    op.drop_index('idx_app_notifications_user_created', table_name='app_notifications')
    # ### end Alembic commands ###
