"""add_note_baby_time_index

Revision ID: e6d3c1a8f902
Revises: c37592925139
Create Date: 2026-02-20 04:49:00.285910+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d3c1a8f902'
down_revision: Union[str, Sequence[str], None] = 'c37592925139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_note_baby_time', 'notes', ['baby_id', 'note_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_note_baby_time', table_name='notes')
    # ### end Alembic commands ###
