"""Fix DailySummary unique constraint for soft deletes

Revision ID: ecd98c6cecdb
Revises: m1n2o3p4
Create Date: 2026-03-15 15:02:08.373396+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecd98c6cecdb'
down_revision: Union[str, Sequence[str], None] = 'm1n2o3p4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('invite_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_families'))
    )
    op.create_index(op.f('ix_families_id'), 'families', ['id'], unique=False)
    op.create_index('ix_families_id_is_deleted', 'families', ['id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_families_invite_code'), 'families', ['invite_code'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('app_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_app_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_notifications'))
    )
    op.create_index('idx_app_notifications_user_created', 'app_notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_app_notifications_user_unread', 'app_notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index(op.f('ix_app_notifications_id'), 'app_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_app_notifications_user_id'), 'app_notifications', ['user_id'], unique=False)
    op.create_index('ix_app_notifications_user_id_is_deleted', 'app_notifications', ['user_id', 'is_deleted'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('babies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('boy', 'girl', 'unknown', name='gender'), nullable=True),
    sa.Column('characteristics', sa.String(), nullable=True),
    sa.Column('feeding_threshold_minutes', sa.Integer(), nullable=True),
    sa.Column('diaper_threshold_minutes', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_babies_family_id_families')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_babies'))
    )
    op.create_index('ix_babies_baby_id_is_deleted', 'babies', ['id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_babies_family_id'), 'babies', ['family_id'], unique=False)
    op.create_index(op.f('ix_babies_id'), 'babies', ['id'], unique=False)
    op.create_table('family_users',
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', 'viewer', name='userrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_family_users_family_id_families')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_family_users_user_id_users')),
    sa.PrimaryKeyConstraint('family_id', 'user_id', name=op.f('pk_family_users'))
    )
    op.create_index(op.f('ix_family_users_user_id'), 'family_users', ['user_id'], unique=False)
    op.create_table('notification_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('family_record_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('feeding_reminder_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('diaper_reminder_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('daily_summary_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('system_notice_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('dnd_start_time', sa.Time(), nullable=True),
    sa.Column('dnd_end_time', sa.Time(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_notification_settings'))
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_push_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscriptions'))
    )
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_index('ix_push_subscriptions_user_id_is_deleted', 'push_subscriptions', ['user_id', 'is_deleted'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_token'), 'user_sessions', ['token'], unique=True)
    op.create_table('baby_achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.String(length=50), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_baby_achievements_baby_id_babies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_baby_achievements_triggered_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baby_achievements')),
    sa.UniqueConstraint('baby_id', 'achievement_id', name='uix_baby_achievement')
    )
    op.create_index('idx_baby_achievements_baby_id', 'baby_achievements', ['baby_id'], unique=False)
    op.create_index(op.f('ix_baby_achievements_baby_id'), 'baby_achievements', ['baby_id'], unique=False)
    op.create_index(op.f('ix_baby_achievements_id'), 'baby_achievements', ['id'], unique=False)
    op.create_table('baby_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_baby_permissions_baby_id_babies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_baby_permissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baby_permissions')),
    sa.UniqueConstraint('baby_id', 'user_id', 'record_type', name='uix_baby_user_record_type')
    )
    op.create_index(op.f('ix_baby_permissions_id'), 'baby_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_baby_permissions_user_id'), 'baby_permissions', ['user_id'], unique=False)
    op.create_table('contraction_timer_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_contraction_timer_states_baby_id_babies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contraction_timer_states')),
    sa.UniqueConstraint('baby_id', name=op.f('uq_contraction_timer_states_baby_id'))
    )
    op.create_index(op.f('ix_contraction_timer_states_id'), 'contraction_timer_states', ['id'], unique=False)
    op.create_table('contractions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_contractions_baby_id_babies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_contractions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contractions'))
    )
    op.create_index('idx_contraction_baby_start_time', 'contractions', ['baby_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_contractions_baby_id'), 'contractions', ['baby_id'], unique=False)
    op.create_index('ix_contractions_baby_id_is_deleted', 'contractions', ['baby_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_contractions_id'), 'contractions', ['id'], unique=False)
    op.create_index(op.f('ix_contractions_start_time'), 'contractions', ['start_time'], unique=False)
    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('generated_content', sa.Text(), nullable=False),
    sa.Column('edited_content', sa.Text(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('image_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_daily_summaries_baby_id_babies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_summaries_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_summaries'))
    )
    op.create_index('ix_daily_summaries_baby_id_is_deleted', 'daily_summaries', ['baby_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_daily_summaries_id'), 'daily_summaries', ['id'], unique=False)
    op.create_index('uix_daily_summary_baby_date_partial', 'daily_summaries', ['baby_id', 'summary_date'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('diapers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('change_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('diaper_type', sa.Enum('WET', 'DIRTY', 'BOTH', 'CLEAN', name='diapertype'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_diapers_baby_id_babies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_diapers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diapers'))
    )
    op.create_index('idx_diaper_baby_time', 'diapers', ['baby_id', 'change_time'], unique=False)
    op.create_index('ix_diapers_baby_id_is_deleted', 'diapers', ['baby_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_diapers_change_time'), 'diapers', ['change_time'], unique=False)
    op.create_index(op.f('ix_diapers_id'), 'diapers', ['id'], unique=False)
    op.create_index(op.f('ix_diapers_user_id'), 'diapers', ['user_id'], unique=False)
    op.create_table('feeding_timer_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('active_side', sa.String(), nullable=True),
    sa.Column('left_elapsed_seconds', sa.Integer(), nullable=False),
    sa.Column('right_elapsed_seconds', sa.Integer(), nullable=False),
    sa.Column('segment_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_feeding_timer_states_baby_id_babies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feeding_timer_states')),
    sa.UniqueConstraint('baby_id', name=op.f('uq_feeding_timer_states_baby_id'))
    )
    op.create_index(op.f('ix_feeding_timer_states_id'), 'feeding_timer_states', ['id'], unique=False)
    op.create_table('feedings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feeding_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feeding_type', sa.Enum('BREAST', 'BOTTLE', 'MIXED', name='feedingtype'), nullable=False),
    sa.Column('amount_ml', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('left_breast_minutes', sa.Integer(), nullable=True),
    sa.Column('right_breast_minutes', sa.Integer(), nullable=True),
    sa.Column('last_breast_side', sa.Enum('LEFT', 'RIGHT', 'BOTH', name='breastside'), nullable=True),
    sa.Column('bottle_content_type', sa.Enum('FORMULA', 'EXPRESSED_MILK', 'MIXED', name='bottlecontenttype'), nullable=True),
    sa.Column('feeding_completion', sa.Enum('FULL', 'PARTIAL', name='feedingcompletion'), nullable=True),
    sa.Column('burped', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_feedings_baby_id_babies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedings'))
    )
    op.create_index('idx_feeding_baby_time', 'feedings', ['baby_id', 'feeding_time'], unique=False)
    op.create_index('ix_feedings_baby_id_is_deleted', 'feedings', ['baby_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_feedings_feeding_time'), 'feedings', ['feeding_time'], unique=False)
    op.create_index(op.f('ix_feedings_id'), 'feedings', ['id'], unique=False)
    op.create_index(op.f('ix_feedings_user_id'), 'feedings', ['user_id'], unique=False)
    op.create_table('growths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('head_circumference', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_growths_baby_id_babies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_growths_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growths'))
    )
    op.create_index('idx_growth_baby_date', 'growths', ['baby_id', 'date'], unique=False)
    op.create_index('ix_growths_baby_id_is_deleted', 'growths', ['baby_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_growths_date'), 'growths', ['date'], unique=False)
    op.create_index(op.f('ix_growths_id'), 'growths', ['id'], unique=False)
    op.create_index(op.f('ix_growths_user_id'), 'growths', ['user_id'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('milestone_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('achieved_date', sa.Date(), nullable=False),
    sa.Column('image_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_milestones_baby_id_babies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_milestones_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestones'))
    )
    op.create_index('idx_milestone_baby_achieved', 'milestones', ['baby_id', 'achieved_date'], unique=False)
    op.create_index(op.f('ix_milestones_achieved_date'), 'milestones', ['achieved_date'], unique=False)
    op.create_index('ix_milestones_baby_id_is_deleted', 'milestones', ['baby_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_milestones_id'), 'milestones', ['id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_notes_baby_id_babies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notes_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index('idx_note_baby_time', 'notes', ['baby_id', 'note_time'], unique=False)
    op.create_index('ix_notes_baby_id_is_deleted', 'notes', ['baby_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_index(op.f('ix_notes_note_time'), 'notes', ['note_time'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('record_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_has_concern', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_record_comments_baby_id_babies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_record_comments_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_record_comments'))
    )
    op.create_index('idx_comment_record', 'record_comments', ['record_type', 'record_id'], unique=False)
    op.create_index(op.f('ix_record_comments_baby_id'), 'record_comments', ['baby_id'], unique=False)
    op.create_index('ix_record_comments_baby_id_is_deleted', 'record_comments', ['baby_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_record_comments_id'), 'record_comments', ['id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_schedules_baby_id_babies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_schedules_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_index('idx_schedule_baby_scheduled_time', 'schedules', ['baby_id', 'scheduled_time'], unique=False)
    op.create_index('ix_schedules_baby_id_is_deleted', 'schedules', ['baby_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_index(op.f('ix_schedules_scheduled_time'), 'schedules', ['scheduled_time'], unique=False)
    op.create_table('sleeps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_sleeps_baby_id_babies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sleeps_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sleeps'))
    )
    op.create_index('idx_sleep_baby_start_time', 'sleeps', ['baby_id', 'start_time'], unique=False)
    op.create_index('ix_sleeps_baby_id_is_deleted', 'sleeps', ['baby_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_sleeps_id'), 'sleeps', ['id'], unique=False)
    op.create_index(op.f('ix_sleeps_start_time'), 'sleeps', ['start_time'], unique=False)
    op.create_index(op.f('ix_sleeps_user_id'), 'sleeps', ['user_id'], unique=False)
    op.create_table('temperature_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('method', sa.Enum('AXILLARY', 'EAR', 'FOREHEAD', 'RECTAL', name='temperaturemethod'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_temperature_records_baby_id_babies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_temperature_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_temperature_records'))
    )
    op.create_index('idx_temperature_baby_time', 'temperature_records', ['baby_id', 'measured_at'], unique=False)
    op.create_index('ix_temperature_records_baby_id_is_deleted', 'temperature_records', ['baby_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_temperature_records_id'), 'temperature_records', ['id'], unique=False)
    op.create_index(op.f('ix_temperature_records_measured_at'), 'temperature_records', ['measured_at'], unique=False)
    op.create_index(op.f('ix_temperature_records_user_id'), 'temperature_records', ['user_id'], unique=False)
    op.create_table('vaccinations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vaccine_name', sa.String(), nullable=False),
    sa.Column('dose_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'POSTPONED', name='vaccinationstatus'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('lot_number', sa.String(), nullable=True),
    sa.Column('hospital_name', sa.String(), nullable=True),
    sa.Column('has_side_effect', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_vaccinations_baby_id_babies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vaccinations_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vaccinations'))
    )
    op.create_index('idx_vaccination_baby_status', 'vaccinations', ['baby_id', 'status'], unique=False)
    op.create_index('ix_vaccinations_baby_id_is_deleted', 'vaccinations', ['baby_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_vaccinations_id'), 'vaccinations', ['id'], unique=False)
    op.create_index(op.f('ix_vaccinations_scheduled_date'), 'vaccinations', ['scheduled_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vaccinations_scheduled_date'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_id'), table_name='vaccinations')
    op.drop_index('ix_vaccinations_baby_id_is_deleted', table_name='vaccinations')
    op.drop_index('idx_vaccination_baby_status', table_name='vaccinations')
    op.drop_table('vaccinations')
    op.drop_index(op.f('ix_temperature_records_user_id'), table_name='temperature_records')
    op.drop_index(op.f('ix_temperature_records_measured_at'), table_name='temperature_records')
    op.drop_index(op.f('ix_temperature_records_id'), table_name='temperature_records')
    op.drop_index('ix_temperature_records_baby_id_is_deleted', table_name='temperature_records')
    op.drop_index('idx_temperature_baby_time', table_name='temperature_records')
    op.drop_table('temperature_records')
    op.drop_index(op.f('ix_sleeps_user_id'), table_name='sleeps')
    op.drop_index(op.f('ix_sleeps_start_time'), table_name='sleeps')
    op.drop_index(op.f('ix_sleeps_id'), table_name='sleeps')
    op.drop_index('ix_sleeps_baby_id_is_deleted', table_name='sleeps')
    op.drop_index('idx_sleep_baby_start_time', table_name='sleeps')
    op.drop_table('sleeps')
    op.drop_index(op.f('ix_schedules_scheduled_time'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_index('ix_schedules_baby_id_is_deleted', table_name='schedules')
    op.drop_index('idx_schedule_baby_scheduled_time', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_record_comments_id'), table_name='record_comments')
    op.drop_index('ix_record_comments_baby_id_is_deleted', table_name='record_comments')
    op.drop_index(op.f('ix_record_comments_baby_id'), table_name='record_comments')
    op.drop_index('idx_comment_record', table_name='record_comments')
    op.drop_table('record_comments')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_note_time'), table_name='notes')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index('ix_notes_baby_id_is_deleted', table_name='notes')
    op.drop_index('idx_note_baby_time', table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_milestones_id'), table_name='milestones')
    op.drop_index('ix_milestones_baby_id_is_deleted', table_name='milestones')
    op.drop_index(op.f('ix_milestones_achieved_date'), table_name='milestones')
    op.drop_index('idx_milestone_baby_achieved', table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_growths_user_id'), table_name='growths')
    op.drop_index(op.f('ix_growths_id'), table_name='growths')
    op.drop_index(op.f('ix_growths_date'), table_name='growths')
    op.drop_index('ix_growths_baby_id_is_deleted', table_name='growths')
    op.drop_index('idx_growth_baby_date', table_name='growths')
    op.drop_table('growths')
    op.drop_index(op.f('ix_feedings_user_id'), table_name='feedings')
    op.drop_index(op.f('ix_feedings_id'), table_name='feedings')
    op.drop_index(op.f('ix_feedings_feeding_time'), table_name='feedings')
    op.drop_index('ix_feedings_baby_id_is_deleted', table_name='feedings')
    op.drop_index('idx_feeding_baby_time', table_name='feedings')
    op.drop_table('feedings')
    op.drop_index(op.f('ix_feeding_timer_states_id'), table_name='feeding_timer_states')
    op.drop_table('feeding_timer_states')
    op.drop_index(op.f('ix_diapers_user_id'), table_name='diapers')
    op.drop_index(op.f('ix_diapers_id'), table_name='diapers')
    op.drop_index(op.f('ix_diapers_change_time'), table_name='diapers')
    op.drop_index('ix_diapers_baby_id_is_deleted', table_name='diapers')
    op.drop_index('idx_diaper_baby_time', table_name='diapers')
    op.drop_table('diapers')
    op.drop_index('uix_daily_summary_baby_date_partial', table_name='daily_summaries', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_daily_summaries_id'), table_name='daily_summaries')
    op.drop_index('ix_daily_summaries_baby_id_is_deleted', table_name='daily_summaries')
    op.drop_table('daily_summaries')
    op.drop_index(op.f('ix_contractions_start_time'), table_name='contractions')
    op.drop_index(op.f('ix_contractions_id'), table_name='contractions')
    op.drop_index('ix_contractions_baby_id_is_deleted', table_name='contractions')
    op.drop_index(op.f('ix_contractions_baby_id'), table_name='contractions')
    op.drop_index('idx_contraction_baby_start_time', table_name='contractions')
    op.drop_table('contractions')
    op.drop_index(op.f('ix_contraction_timer_states_id'), table_name='contraction_timer_states')
    op.drop_table('contraction_timer_states')
    op.drop_index(op.f('ix_baby_permissions_user_id'), table_name='baby_permissions')
    op.drop_index(op.f('ix_baby_permissions_id'), table_name='baby_permissions')
    op.drop_table('baby_permissions')
    op.drop_index(op.f('ix_baby_achievements_id'), table_name='baby_achievements')
    op.drop_index(op.f('ix_baby_achievements_baby_id'), table_name='baby_achievements')
    op.drop_index('idx_baby_achievements_baby_id', table_name='baby_achievements')
    op.drop_table('baby_achievements')
    op.drop_index(op.f('ix_user_sessions_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_push_subscriptions_user_id_is_deleted', table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_family_users_user_id'), table_name='family_users')
    op.drop_table('family_users')
    op.drop_index(op.f('ix_babies_id'), table_name='babies')
    op.drop_index(op.f('ix_babies_family_id'), table_name='babies')
    op.drop_index('ix_babies_baby_id_is_deleted', table_name='babies')
    op.drop_table('babies')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_app_notifications_user_id_is_deleted', table_name='app_notifications')
    op.drop_index(op.f('ix_app_notifications_user_id'), table_name='app_notifications')
    op.drop_index(op.f('ix_app_notifications_id'), table_name='app_notifications')
    op.drop_index('idx_app_notifications_user_unread', table_name='app_notifications')
    op.drop_index('idx_app_notifications_user_created', table_name='app_notifications')
    op.drop_table('app_notifications')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_families_invite_code'), table_name='families')
    op.drop_index('ix_families_id_is_deleted', table_name='families')
    op.drop_index(op.f('ix_families_id'), table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###
