"""
Core constants for the application.
"""

# Pagination
DEFAULT_PAGINATION_LIMIT = 20
MAX_PAGINATION_LIMIT = 100

# API
API_TIMEOUT_MS = 30000

# Validation
FUTURE_DATE_BUFFER_MIN = 5
NOTE_MAX_LENGTH = 2000
MAX_FEEDING_ML = 500
MAX_FEEDING_DURATION_MINUTES = 300  # 5 hours
MAX_BREAST_FEEDING_MINUTES = 120  # 2 hours per side
MAX_SLEEP_HOURS = 18
GROWTH_HEIGHT_MIN_CM = 30.0
USERNAME_MIN_LENGTH = 3

# AI Parameters
AI_SUMMARY_CHARS_MIN = 100
AI_SUMMARY_CHARS_MAX = 200
AI_TEMPERATURE = 0.7
AI_MAX_TOKENS = 800

# API Rate Limits
RATE_LIMIT_LOGIN_REQUESTS = 5
RATE_LIMIT_LOGIN_WINDOW = 60

RATE_LIMIT_CHANGE_PASSWORD_REQUESTS = 3
RATE_LIMIT_CHANGE_PASSWORD_WINDOW = 60

RATE_LIMIT_REGISTER_REQUESTS = 3
RATE_LIMIT_REGISTER_WINDOW = 60

RATE_LIMIT_AI_FEEDBACK_REQUESTS = 5
RATE_LIMIT_AI_FEEDBACK_WINDOW = 60

RATE_LIMIT_COMMENT_REQUESTS = 10
RATE_LIMIT_COMMENT_WINDOW = 60

RATE_LIMIT_NOTIFICATION_REQUESTS = 3
RATE_LIMIT_NOTIFICATION_WINDOW = 60

RATE_LIMIT_RESET_PASSWORD_REQUESTS = 3
RATE_LIMIT_RESET_PASSWORD_WINDOW = 60

RATE_LIMIT_REGENERATE_INVITE_REQUESTS = 5
RATE_LIMIT_REGENERATE_INVITE_WINDOW = 60

RATE_LIMIT_AI_SUMMARY_REQUESTS = 5
RATE_LIMIT_AI_SUMMARY_WINDOW = 60

RATE_LIMIT_UPLOAD_REQUESTS = 10
RATE_LIMIT_UPLOAD_WINDOW = 60

RATE_LIMIT_VACCINATION_GENERATE_REQUESTS = 3
RATE_LIMIT_VACCINATION_GENERATE_WINDOW = 60
RATE_LIMIT_VACCINATION_CREATE_REQUESTS = 10
RATE_LIMIT_VACCINATION_CREATE_WINDOW = 60

RATE_LIMIT_JOIN_FAMILY_REQUESTS = 10
RATE_LIMIT_JOIN_FAMILY_WINDOW = 3600
