"""
Core constants for the application.
"""

# Pagination
DEFAULT_PAGINATION_LIMIT = 20
MAX_PAGINATION_LIMIT = 100

# API
API_TIMEOUT_MS = 30000

# Validation
FUTURE_DATE_BUFFER_MIN = 5
NOTE_MAX_LENGTH = 2000
MAX_FEEDING_ML = 500
MAX_SLEEP_HOURS = 18
GROWTH_HEIGHT_MIN_CM = 30.0
USERNAME_MIN_LENGTH = 3

# AI Parameters
AI_SUMMARY_CHARS_MIN = 100
AI_SUMMARY_CHARS_MAX = 200
AI_TEMPERATURE = 0.7
AI_MAX_TOKENS = 800
